feat: move icons into sharepoint
hlxsites/mammotome pull request #157
Opened 2023-05-26 09:51 UTC by dzehnder

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #83 

Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/en/
- After: https://83-move-icons--mammotome--hlxsites.hlx.page/en/

2023-05-26 09:59 UTC, Acidham requested changes
@dzehnder you also moved logo.svg, but there are two different flavors of the Mammotome logo, the wide version and the small version. To be consistent, I would expect to upload/change the small version as well?

2023-05-26 15:32 UTC, Acidham commented on blocks/header/header.js
I would call it `logo-light` or `logo-small` and the logic would be that `:logo:` in word doc will be extended with `-light` resp. `-small`

2023-05-30 10:12 UTC, dzehnder commented on blocks/header/header.js
The only place where it is used is in combination with custom code, i.e when the user scrolls down. 
I don't think it is the right approach to make the author responsible for that as it is more of a design decition.

2023-06-08 06:37 UTC, solaris007 approved these changes

2023-06-09 11:08 UTC, solaris007 commented
@dzehnder anything else required?

2023-06-14 12:13 UTC, merged