feat: adding overlay picture
hlxsites/mammotome pull request #219
Opened 2023-06-08 15:41 UTC by dzehnder

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #183 
Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/about-us/news-media-category/mammotome-one-voice
- After: https://<branch>--mammotome--hlxsites.hlx.page/us/en/about-us/news-media-category/mammotome-one-voice

2023-06-09 11:07 UTC, solaris007 submitted a review, later dismissed

2023-06-09 13:46 UTC, Acidham requested changes
the image seems to be too high

<img width="512" alt="Screenshot 2023-06-09 at 15 44 33" src="https://github.com/hlxsites/mammotome/assets/17712121/1e292113-d76e-4175-a2a6-7723cd403181">

2023-06-14 12:36 UTC, solaris007 approved these changes

2023-06-14 12:59 UTC, Acidham approved these changes

2023-06-14 14:47 UTC, merged