Section styles for mobile
hlxsites/mammotome pull request #279
Opened 2023-06-19 11:58 UTC by Acidham

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #265 

Test URLs:
- Before: 
- https://main--mammotome--hlxsites.hlx.page/us/en/healthcare-professionals/webinars
- https://main--mammotome--hlxsites.hlx.page/us/en/products/mammotome-confirm

- After: 
- https://265-style-scaling-for-mobile--mammotome--hlxsites.hlx.page/us/en/healthcare-professionals/webinars
- https://265-style-scaling-for-mobile--mammotome--hlxsites.hlx.page/us/en/products/mammotome-confirm

2023-06-19 13:35 UTC, dzehnder commented on styles/styles.css
> +    font-size: var(--mt-heading-font-size-xxl);
Same font size for h1-h3?

2023-06-19 13:36 UTC, dzehnder submitted a review, later dismissed

2023-06-19 13:47 UTC, chicharr requested changes
@Acidham changes look good to me. However, there are some differences in the appearance of the headings compared to Mammotome.com. Please check https://github.com/hlxsites/mammotome/pull/279#issuecomment-1597223058

2023-06-19 15:02 UTC, Acidham commented on styles/styles.css
> +    font-size: var(--mt-heading-font-size-xxl);
this is how @smiroslav  implemented it

2023-06-20 12:45 UTC, Acidham commented
@chicharr yes it looks different, but MT uses different sizes for desktop and mobile. When I change a downsizing of the font for H1 for example, it must be the same across the page. Webinars behaves now same like Mammotome Confirm.

2023-06-20 13:27 UTC, chicharr approved these changes
@Acidham As agreed on slack, please open a new issue to tackle the padding in the headings for the product pages on mobile. See https://main--mammotome--hlxsites.hlx.page/us/en/products/mammotome-confirm.
In original site, in mobile view, the heading 1 is split in 2 lines due to the padding

2023-06-20 14:39 UTC, chicharr approved these changes
LGTM. As discussed on slack this change is setting a uniform h1 font-size across products and other pages. This is in practice making the title on the Webinars page smaller.
@Acidham  as please ask Krizel if she is ok to make the heading 1 font-size uniform for products and other pages

2023-06-20 14:43 UTC, merged