fix: IFU result buttons text uppercase
hlxsites/mammotome pull request #359
Opened 2023-06-28 13:24 UTC by solaris007

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #310 

Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/ifu-index
- After: https://310-eifu-buttons--mammotome--hlxsites.hlx.page/us/en/ifu-index

2023-06-28 14:11 UTC, karlpauls approved these changes

2023-06-28 14:45 UTC, dzehnder requested changes
This change does not seem to have an effect for me: 
![Screenshot 2023-06-28 at 16 45 17](https://github.com/hlxsites/mammotome/assets/16799758/68300b80-8967-4ec4-948b-cd4e513228cb)

2023-06-29 05:34 UTC, solaris007 commented
@dzehnder the change should only apply to the file download buttons in a search result, not the search form buttons. kindly re-consider your approval.

2023-06-29 12:20 UTC, Acidham approved these changes

2023-06-29 13:19 UTC, dzehnder approved these changes

2023-06-29 18:42 UTC, merged