feat: refresh style footer
hlxsites/mammotome pull request #500
Opened 2023-07-20 09:53 UTC by solaris007

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #497 

Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/drafts/
- After: https://497-restyle-footer--mammotome--hlxsites.hlx.page/us/en/drafts/

2023-07-20 10:59 UTC, solaris007 commented
CLS identified, working on it

2023-07-21 10:44 UTC, Acidham requested changes
CSS variables need to be aligned to the nomenclature. see review comments in css

2023-07-21 10:44 UTC, Acidham commented on blocks/footer/footer.css
> +  color: var(--mt-background-color-primary);
Header color should be `--mt-heading-color-inverted` instead of `--mt-background-color-primary`

2023-07-21 10:44 UTC, Acidham commented on blocks/footer/footer.css
> +  color: var(--mt-background-color-primary);
Better to introduce a `svg color` var

2023-07-21 10:44 UTC, Acidham commented on blocks/footer/footer.css
>    margin-top: unset;
same like above re h1 color

2023-07-21 10:44 UTC, Acidham commented on blocks/footer/footer.css
> +  color: var(--mt-background-color-primary);
Introduce link-color-inverted instead of using background color

2023-07-21 10:47 UTC, Acidham commented
Maybe logo needs to be aligned left in mobile view similar to the current design?

<img width="479" alt="Screenshot 2023-07-21 at 12 46 01" src="https://github.com/hlxsites/mammotome/assets/17712121/0e8ce657-1ade-478f-8fb2-c3cd509394b7">

Current:

<img width="488" alt="Screenshot 2023-07-21 at 12 47 10" src="https://github.com/hlxsites/mammotome/assets/17712121/905dcb82-f614-45e9-9b32-4bcba5f288a0">

2023-07-21 11:09 UTC, solaris007 commented
> Maybe logo needs to be aligned left in mobile view similar to the current design?

No, the new design has a diagonal relationship between small and big logo. also, they approved the breakpoints yesterday during demo.

2023-07-21 12:40 UTC, Acidham approved these changes

2023-07-21 12:41 UTC, merged